### ISSUE TITLE
Does this also include co-authors

### ISSUE THREAD

**Issue by timmwille** [hoijui/reuseify#1]
I've recently discovered co-authors, especially when projects are made by many people but only one knows how to use git or is responsible for pushing the sources to git, it can be very useful for respecting all "copyleft owners" so to say to reference everyone involved.

Would this code also include such info?

https://www.30secondsofcode.org/articles/s/github-co-authors/

**Comment by hoijui** [comment]
not yet.

There is a function built into git proper, that does almost the same thing; it is called "signing off".
It just uses a different indicator string: "Signed-off-by" instead of "Co-authored-by".

I will implement both at once.
